# Generated by Django 3.2 on 2021-04-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='date_birth',
            field=models.DateField(),
        ),
    ]
