# Generated by Django 3.2 on 2021-05-04 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warcraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('military_area', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('start_pose', models.CharField(max_length=100)),
                ('end_pose', models.CharField(max_length=100)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warcrafts', to='accounts.dossier')),
            ],
        ),
    ]
